name: Execution tests

on:
  push:
    branches:
      - master
      - release
      - test
      - dev-main

jobs:
  executionTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/pypack_requirements.txt
    - name: Test status checking script
      run: python get_status.py
