name: Packaging Test

on:
  push:
    branches: [ master, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f pypack-requirements.txt ]; then pip install -r pypack-requirements.txt; fi

    - name: Build and check package
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
