name: Packaging Test

on:
  push:
    branches: [ master, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/pypack_requirements.txt

    - name: Build Package
      run: python setup.py sdist bdist_wheel
    
    - name: Check Package
      run: twine check dist/*
